# Generated by Django 6.0.7 on 2026-07-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalory',
            new_name='Category',
        ),
    ]
