# Generated by Django 6.0.7 on 2026-08-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_shippingaddress_options_alter_category_is_sub_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Quản lý đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Chi tiết đơn hàng', 'verbose_name_plural': 'Chi tiết đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Danh sách sản phẩm'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='product', to='app.category', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(default=0, help_text='Đơn vị: VND', verbose_name='Giá'),
        ),
    ]
